"""initial schema

Revision ID: 5594a5dcdd08
Revises: 
Create Date: 2026-09-20 20:48:40.327258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5594a5dcdd08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('MicrosoftId', sa.String(length=100), nullable=False),
    sa.Column('ResidentialAddress', sa.Text(), nullable=True),
    sa.Column('ProfilePic', sa.String(length=255), nullable=True),
    sa.Column('CellphoneNumber', sa.String(length=20), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('LastLogin', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('MicrosoftId')
    )
    op.create_table('budgets',
    sa.Column('BudgetId', sa.String(length=30), nullable=False),
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('UsedAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ClosedDate', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('BudgetId')
    )
    op.create_table('preferences',
    sa.Column('PreferenceId', sa.String(length=30), nullable=False),
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('PreferenceType', sa.String(length=50), nullable=False),
    sa.Column('PreferenceValue', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PreferenceId')
    )
    op.create_table('shopping_lists',
    sa.Column('ShoppingListId', sa.String(length=30), nullable=False),
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('BudgetId', sa.String(length=30), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('TotalCost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('DateClosed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['BudgetId'], ['budgets.BudgetId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ShoppingListId')
    )
    op.create_table('sub_budgets',
    sa.Column('SubBudgetId', sa.String(length=30), nullable=False),
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('BudgetId', sa.String(length=30), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('AllocatedAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('UsedAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ClosedDate', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['BudgetId'], ['budgets.BudgetId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubBudgetId')
    )
    op.create_table('list_items',
    sa.Column('ListItemId', sa.String(length=30), nullable=False),
    sa.Column('UserId', sa.String(length=30), nullable=False),
    sa.Column('ShoppingListId', sa.String(length=30), nullable=False),
    sa.Column('SubBudgetId', sa.String(length=30), nullable=True),
    sa.Column('ItemName', sa.String(length=150), nullable=False),
    sa.Column('UnitCost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ItemQuantity', sa.Integer(), nullable=False),
    sa.Column('StoreName', sa.String(length=100), nullable=True),
    sa.Column('ItemImage', sa.String(length=255), nullable=True),
    sa.Column('BarCode', sa.String(length=50), nullable=True),
    sa.Column('StoreAddress', sa.Text(), nullable=True),
    sa.Column('StoreLink', sa.String(length=255), nullable=True),
    sa.Column('CheaperAlternativeJSON', sa.JSON(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ShoppingListId'], ['shopping_lists.ShoppingListId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SubBudgetId'], ['sub_budgets.SubBudgetId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ListItemId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_items')
    op.drop_table('sub_budgets')
    op.drop_table('shopping_lists')
    op.drop_table('preferences')
    op.drop_table('budgets')
    op.drop_table('users')
    # ### end Alembic commands ###
