"""step 3 auth columns

Revision ID: 740e2c05654b
Revises: 5594a5dcdd08
Create Date: 2026-09-20 21:16:48.936233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740e2c05654b'
down_revision = '5594a5dcdd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PasswordHash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('SAIdHash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('SAIdLast4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('DateOfBirth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('Gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Race', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('TermsAcceptedOn', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('MicrosoftId',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint('uq_users_SAIdHash', ['SAIdHash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_SAIdHash', type_='unique')
        batch_op.alter_column('MicrosoftId',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('TermsAcceptedOn')
        batch_op.drop_column('Race')
        batch_op.drop_column('Gender')
        batch_op.drop_column('DateOfBirth')
        batch_op.drop_column('SAIdLast4')
        batch_op.drop_column('SAIdHash')
        batch_op.drop_column('PasswordHash')

    # ### end Alembic commands ###
