"""step 4 user location

Revision ID: 94353d8272ef
Revises: 740e2c05654b
Create Date: 2026-09-20 21:19:23.569820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94353d8272ef'
down_revision = '740e2c05654b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Longitude')
        batch_op.drop_column('Latitude')

    # ### end Alembic commands ###
