"""step 7 stores

Revision ID: d6526d03a521
Revises: 94353d8272ef
Create Date: 2026-09-20 21:28:12.165325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6526d03a521'
down_revision = '94353d8272ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('StoreId', sa.String(length=30), nullable=False),
    sa.Column('Slug', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Brand', sa.String(length=50), nullable=False),
    sa.Column('Suburb', sa.String(length=100), nullable=True),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('LocationSource', sa.String(length=20), nullable=False),
    sa.Column('Phone', sa.String(length=30), nullable=True),
    sa.Column('OpeningHours', sa.String(length=255), nullable=True),
    sa.Column('StoreLink', sa.String(length=255), nullable=True),
    sa.Column('DateCreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('StoreId'),
    sa.UniqueConstraint('Slug')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_Brand'), ['Brand'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_Brand'))

    op.drop_table('stores')
    # ### end Alembic commands ###
